time_project:
    resource: "@TimeProjectBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /login
    defaults:  { _controller: OCUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

#fos_user_security_login:
#    path:  /login
#
#fos_user_security_check:
#    path:   /login_check

change_password:
    path: /profile/change-password
    defaults: { _controller: OCUserBundle:ChangePassword:changePassword }

fos_user_security:
    resource:  "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource:  "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:  /profile

fos_user_registration_register:
    resource:  "@OCUserBundle/Resources/config/routing/registration.xml"
    prefix:  /register

fos_user_resetting:
    resource:  "@OCUserBundle/Resources/config/routing/resetting.xml"
    prefix:  /resetting

fos_user_change_password:
    resource:  "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:  /profile/change-password

fos_user_profile_edit:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile/edit