time_project_homepage:
    path:     /
    defaults: { _controller: TimeProjectBundle:Default:index }

create_user:
    path: /create_user
    defaults: { _controller: TimeProjectBundle:Default:createUser }

get_all_users:
    path: /get_all_users
    defaults : { _controller: TimeProjectBundle:Default:getAllUsers }

manage_user:
    path: /manage_user
    defaults : { _controller: TimeProjectBundle:Default:manageUser }

project_calendar:
    path: /project_calendar/projet-{project_id}
    defaults: { _controller: TimeProjectBundle:Default:getProjectCalendar }
    requirements:
        project_id: '\d+'

create_project:
    path: /create_project
    defaults: { _controller: TimeProjectBundle:Default:createProject }

create_tache:
    path: /create_tache
    defaults: { _controller: TimeProjectBundle:Default:createTache }

edit_tache:
    path: /edit_tache
    defaults: { _controller: TimeProjectBundle:Default:editTache }

list_plan:
    path: /list_plan/projet-{project_id}
    defaults: { _controller: TimeProjectBundle:Default:listPlan }
    requirements:
        project_id: '\d+'

page_introuvable:
    path: error-404
    defaults: { _controller: TimeProjectBundle:Default:pageIntrouvable }

get_taches:
    path: /getTaches/{projetId}/{priorite}
    defaults: { _controller: TimeProjectBundle:Default:getTaches }
    requirements:
        projetId: '\d+'
        priorite: '\d+'