<?php

namespace Proxies\__CG__\TimeProjectBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notification extends \TimeProjectBundle\Entity\Notification implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idnotification', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'intituleTitre', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'contenu', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'isvalidation', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'iddate', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idmission', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idcategorieMission', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idemploye', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idsociete', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idadmin'];
        }

        return ['__isInitialized__', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idnotification', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'intituleTitre', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'contenu', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'isvalidation', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'iddate', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idmission', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idcategorieMission', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idemploye', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idsociete', '' . "\0" . 'TimeProjectBundle\\Entity\\Notification' . "\0" . 'idadmin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Notification $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdnotification()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdnotification();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdnotification', []);

        return parent::getIdnotification();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntituleTitre($intituleTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntituleTitre', [$intituleTitre]);

        return parent::setIntituleTitre($intituleTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntituleTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntituleTitre', []);

        return parent::getIntituleTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu($contenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', [$contenu]);

        return parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', []);

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsvalidation($isvalidation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsvalidation', [$isvalidation]);

        return parent::setIsvalidation($isvalidation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsvalidation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsvalidation', []);

        return parent::getIsvalidation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIddate($iddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIddate', [$iddate]);

        return parent::setIddate($iddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getIddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddate', []);

        return parent::getIddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmission($idmission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmission', [$idmission]);

        return parent::setIdmission($idmission);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmission', []);

        return parent::getIdmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcategorieMission($idcategorieMission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcategorieMission', [$idcategorieMission]);

        return parent::setIdcategorieMission($idcategorieMission);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcategorieMission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcategorieMission', []);

        return parent::getIdcategorieMission();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdemploye($idemploye)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdemploye', [$idemploye]);

        return parent::setIdemploye($idemploye);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdemploye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdemploye', []);

        return parent::getIdemploye();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsociete($idsociete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsociete', [$idsociete]);

        return parent::setIdsociete($idsociete);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsociete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsociete', []);

        return parent::getIdsociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdadmin(\TimeProjectBundle\Entity\Admin $idadmin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdadmin', [$idadmin]);

        return parent::setIdadmin($idadmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdadmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdadmin', []);

        return parent::getIdadmin();
    }

}
