<?php

namespace Proxies\__CG__\TimeProjectBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Societe extends \TimeProjectBundle\Entity\Societe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'idsociete', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'nom', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'adresse', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'societecol', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'idadmin', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'idsecteurSociete'];
        }

        return ['__isInitialized__', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'idsociete', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'nom', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'adresse', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'societecol', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'idadmin', '' . "\0" . 'TimeProjectBundle\\Entity\\Societe' . "\0" . 'idsecteurSociete'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Societe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdsociete()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdsociete();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsociete', []);

        return parent::getIdsociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocietecol($societecol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocietecol', [$societecol]);

        return parent::setSocietecol($societecol);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocietecol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocietecol', []);

        return parent::getSocietecol();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdadmin(\TimeProjectBundle\Entity\Admin $idadmin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdadmin', [$idadmin]);

        return parent::setIdadmin($idadmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdadmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdadmin', []);

        return parent::getIdadmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsecteurSociete(\TimeProjectBundle\Entity\SecteurSociete $idsecteurSociete = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsecteurSociete', [$idsecteurSociete]);

        return parent::setIdsecteurSociete($idsecteurSociete);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsecteurSociete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsecteurSociete', []);

        return parent::getIdsecteurSociete();
    }

}
